Errors for External Service Tasks
bpmn-io/bpmn-properties-panel pull request #108
Opened 2021-09-14 07:08 UTC by philippfromme

# Changes

* add _Errors_ group for external service tasks
* fix select empty state for global elements

<img alt="chrome_DBfRs71M3e" src="https://user-images.githubusercontent.com/7633572/133211418-2efadf94-4d9d-4642-9a1b-11ed5a125abd.png">

2021-09-15 14:53 UTC, philippfromme commented
I found an issue with the edited state after applying the fix to the selects. The empty value is now `empty` instead of an empty string. `isEdited` interprets that as edited. It should be configurable like:

```javascript
function isEdited(node, emptyValue = '') {
  return node && node.value !== emptyValue;
}

isEdited(node, 'empty');
```

2021-09-17 11:35 UTC, MaxTru commented
General question / suggestion: 
* Would it not make sense to call the Section `Throw errors`? I think the current label `Errors` does not convey the message, that a user can specify which error shall be thrown based on a expression provided. Also cf. the [docs about this](https://docs.camunda.org/manual/7.15/user-guide/process-engine/external-tasks/#error-event-definitions)

WDYT? @philippfromme @andreasgeier @nikku

2021-09-17 11:39 UTC, MaxTru commented
The error is not cleaned up, when we switch away from Implementationtype==external. Is there already a behavior that does this / or do we have an issue to create such a behavior?

2021-09-17 11:41 UTC, philippfromme commented
@MaxTru I've copied the labels from the old properties panel:

<img alt="Camunda_Modeler_KSyTSuugUD" src="https://user-images.githubusercontent.com/7633572/133776812-be217930-855e-4438-9b57-85c82952e7e7.png">

I just noticed that the error label shows the error code if it has been set. That part is actually missing in my implementation. Shall I adjust it?

2021-09-17 11:42 UTC, MaxTru commented on src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js
> +      ErrorsGroup(element),
Should we not add a testcase in CamundaPlatformPropertiesProvider.spec.js ?

2021-09-17 11:45 UTC, MaxTru commented on src/provider/camunda-platform/properties/Error.js
> +    label: translate('Throw Expression'),
Sentence case should be the new standard
```suggestion
    label: translate('Throw expression'),
```

2021-09-17 11:47 UTC, MaxTru commented on src/provider/camunda-platform/properties/Error.js
> +    label: translate('Global Error Reference'),
```
    label: translate('Global error reference'),
```

2021-09-17 11:49 UTC, MaxTru commented on src/provider/camunda-platform/properties/Error.js
> +    autoFocusEntry: 'errorName',
This has no effect for me. E.g., if I uncollapse an error entry (which has a reference), the errorName is not focussed. Also, should it not be the throwExpression, that is automatically selected once I create a new error?

2021-09-17 11:53 UTC, MaxTru commented
> @MaxTru I've copied the labels from the old properties panel:
> 
> ![Camunda_Modeler_KSyTSuugUD](https://user-images.githubusercontent.com/7633572/133776812-be217930-855e-4438-9b57-85c82952e7e7.png)
> 
> I just noticed that the error label shows the error code if it has been set. That part is actually missing in my implementation. Shall I adjust it?

Yeah, let's do that. I remember that back then we decided to deliberately include it, after consultants explained us, that the code is the one important attribute about an error (because it is used for correlation)

2021-09-17 12:32 UTC, philippfromme commented on src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js
> +      ErrorsGroup(element),
You're right, I just realized, that we test this as well. Will add tests!

2021-09-17 12:42 UTC, philippfromme commented on src/provider/camunda-platform/properties/Error.js
> +    autoFocusEntry: 'errorName',
This should actually be `idPrefix + "-errorName"`. Good catch!

2021-09-17 12:54 UTC, philippfromme commented on src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js
> +      ErrorsGroup(element),
Done (cf. https://github.com/bpmn-io/bpmn-properties-panel/pull/108/files#diff-3e285c619700ed55ad027c61886b2c397ce0defbe03746dae9debefb028869ec).

2021-09-17 12:55 UTC, philippfromme commented on src/provider/camunda-platform/properties/Error.js
> +    label: translate('Throw Expression'),
Done (cf. https://github.com/bpmn-io/bpmn-properties-panel/pull/108/files#diff-e9ae2a1607ddb924b0430102a13f4e6591870d01ce2777ba90d86e146ea9c816R94).

2021-09-17 12:55 UTC, philippfromme commented on src/provider/camunda-platform/properties/Error.js
> +    label: translate('Global Error Reference'),
Done (cf. https://github.com/bpmn-io/bpmn-properties-panel/pull/108/files#diff-e9ae2a1607ddb924b0430102a13f4e6591870d01ce2777ba90d86e146ea9c816R192).

2021-09-17 12:56 UTC, philippfromme commented on src/provider/camunda-platform/properties/Error.js
> +    autoFocusEntry: 'errorName',
Done (cf. https://github.com/bpmn-io/bpmn-properties-panel/pull/108/files#diff-e9ae2a1607ddb924b0430102a13f4e6591870d01ce2777ba90d86e146ea9c816R193).

2021-09-20 10:41 UTC, barmac commented
There's a merge conflict ;(

2021-09-20 11:39 UTC, philippfromme commented
> There's a merge conflict ;(

Will resolve. 👍🏻

2021-09-22 20:12 UTC, MaxTru commented
> The error is not cleaned up, when we switch away from Implementationtype==external. Is there already a behavior that does this / or do we have an issue to create such a behavior?

I couldn't find such a behavior and created a task in https://github.com/bpmn-io/bpmn-properties-panel/issues/2 to:
> Behavior that cleans up errors if implementationType is switched away from external

2021-09-22 20:17 UTC, MaxTru commented on test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider.spec.js
> +    describe.only('process', function() {
```suggestion
    describe('process', function() {
```

2021-09-22 20:21 UTC, MaxTru commented
The errors are currently alphabetically sorted by name (when re-opened). Should we not disable this sorting for errors, since the XML order has a meaning (e.g., the first error which matches the condition, will throw, but not the second one)?

2021-09-23 06:16 UTC, pinussilvestrus commented
> > The error is not cleaned up, when we switch away from Implementationtype==external. Is there already a behavior that does this / or do we have an issue to create such a behavior?
> 
> FYI: I couldn't find such a behavior and created a task in #2 to:
> 
> > Behavior that cleans up errors if implementationType is switched away from external

I think we have one: https://github.com/camunda/camunda-bpmn-js/blob/main/lib/camunda-platform/features/modeling/behavior/DeleteErrorEventDefinitionBehavior.js

2021-09-23 06:21 UTC, MaxTru commented
> > > The error is not cleaned up, when we switch away from Implementationtype==external. Is there already a behavior that does this / or do we have an issue to create such a behavior?
> > 
> > 
> > FYI: I couldn't find such a behavior and created a task in #2 to:
> > > Behavior that cleans up errors if implementationType is switched away from external
> 
> I think we have one: https://github.com/camunda/camunda-bpmn-js/blob/main/lib/camunda-platform/features/modeling/behavior/DeleteErrorEventDefinitionBehavior.js

Ups - that is great.

Sorry for the confusion everyone :-)

2021-09-23 12:20 UTC, MaxTru requested changes
only thing missing: https://github.com/bpmn-io/bpmn-properties-panel/pull/108#discussion_r714278352

2021-09-23 17:13 UTC, andreasgeier commented
UX feedback:

1. I miss the message input. Has it been forgotten?
2. I miss the code part in the list item title (that is already [mentioned above](https://github.com/bpmn-io/bpmn-properties-panel/pull/108#issuecomment-921730347))
3. If the order of errors matters, we cannot use the alphabetical sort here. But since this is a general topic and [under discussion in another issue](https://github.com/bpmn-io/properties-panel/issues/96), we might fix that outside of this PR?
2. I know that the form structure reflects 1:1 what we have in the old panel. However, it breaks the list concept/structure where the first field of a list item always defines the list item title. So, from a UX perspective, it makes sense to have the global error reference select as the first form element and the throw expression at the end (below the select-related inputs). I also assume it would be the logical order: first define/reference the element (the global error), then the condition (the throw expression). Would that be okay from the developer's perspective, too?
3. The empty state label of a newly created item should be <no reference> (angle brackets) in line with <none> and <empty> that we already use in other lists and selects.

2021-09-23 17:20 UTC, MaxTru commented
> If the order of errors matters, we cannot use the alphabetical sort here. But since this is a general topic and under discussion in another issue, we might fix that outside of this PR?

Yep, let's please ignore that here, since we will resolve this for all cases based on this issue: https://github.com/bpmn-io/properties-panel/issues/96

2021-09-26 20:35 UTC, philippfromme commented
@andreasgeier I've applied the changes you requested. The only issue is that now the first entry is the select, which cannot be auto-focused. Therefore, we can either auto-focus the expression input or no input.

![XHxyKbzOW3](https://user-images.githubusercontent.com/7633572/134823273-df43ffc0-fe07-4401-a1f4-fb1227b129cc.gif)

2021-09-27 09:04 UTC, philippfromme commented
`<select>` elements will be auto-focusable: https://github.com/bpmn-io/properties-panel/pull/101

This PR now depends on https://github.com/bpmn-io/properties-panel/pull/101.

2021-10-04 14:53 UTC, philippfromme commented
@MaxTru Awaiting your approval.

2021-10-04 18:43 UTC, MaxTru commented on test/spec/BpmnPropertiesPanelRenderer.spec.js
> +      console.log(xml);
I think this was forgotten here :-)

2021-10-04 18:44 UTC, philippfromme commented on test/spec/BpmnPropertiesPanelRenderer.spec.js
> +      console.log(xml);
Argh!

2021-10-04 18:48 UTC, philippfromme commented on test/spec/BpmnPropertiesPanelRenderer.spec.js
> +      console.log(xml);
Removed. 👍🏻

2021-10-04 18:50 UTC, MaxTru approved these changes
:clap:

2021-10-05 06:58 UTC, merged

2021-10-05 06:59 UTC, pinussilvestrus commented
✌️