Migrate task listener
bpmn-io/bpmn-properties-panel pull request #120
Opened 2021-09-27 12:16 UTC by smbea

Closes #106

2021-09-27 14:27 UTC, barmac commented on src/provider/camunda-platform/properties/ListenerProps.js
> +
I like it.

2021-09-27 14:33 UTC, smbea commented on src/provider/camunda-platform/properties/ListenerProps.js
> +      const id = `${element.id}-listener-${index}`;
Should we do `${element.id}-executionlistener-${index}` or `${element.id}-tasklistener-${index}` then?

2021-09-27 17:27 UTC, barmac commented on src/provider/camunda-platform/properties/ListenerProps.js
> +      const id = `${element.id}-listener-${index}`;
It could be ...-executionListener-... and ...-taskListener-..., but the most important is that the ids are different.

2021-09-27 19:12 UTC, smbea commented on src/provider/camunda-platform/properties/ListenerProps.js
> +      const id = `${element.id}-listener-${index}`;
I updated the ids

2021-09-28 08:54 UTC, barmac commented on src/provider/camunda-platform/properties/ListenerProps.js
> +    if (listener.$type == 'camunda:TaskListener') {
```suggestion
    if (is(listener, 'camunda:TaskListener')) {
```

We don't want to depend on internals.

2021-09-28 08:59 UTC, barmac commented on src/provider/camunda-platform/utils/ImplementationTypeUtils.js
> +  if (is(businessObject, 'camunda:ExecutionListener') || is(businessObject,'camunda:TaskListener')) {
There will be probably no more types of listeners, but generally we could use `isAny` for multiple types check.

2021-09-28 08:59 UTC, barmac commented
Just one more comment to address and we are ready to merge this.

2021-10-01 07:40 UTC, andreasgeier requested changes
The UI looks as expected.

But functional-wise, I miss the timer-related properties (type + definition) when creating a task listener of type timeout.

2021-10-05 08:50 UTC, smbea commented
@barmac I made the changes to use `is` and `isAny`
@andreasgeier I added the timer related properties:

<img width="234" alt="Screenshot 2021-10-05 at 10 20 09" src="https://user-images.githubusercontent.com/25825387/135986717-ba1ec0c5-1047-403a-ae7d-8f2ce7c48908.png">

This resulted in some changes since the last review, specifically in the TimerProps and ListenerProps

2021-10-05 09:11 UTC, andreasgeier approved these changes
✅ &nbsp; LGTM

2021-10-05 11:18 UTC, barmac commented on src/provider/camunda-platform/properties/ListenerProps.js
> +      businessObject: getBusinessObject(listener),
Listener is always a business object, so there's no need to call the helper here.

Generally speaking, we have two types of complex objects in bpmn-js:
* diagram-js objects: shapes, connections -> which have a property called `businessObject` linking to the second type
* bpmn-js business objects: bpmn:Event-s, bpmn:Task-s and so on -> these are objects which are serialized; they don't have `businessObject` ever

2021-10-05 11:58 UTC, barmac commented on src/provider/camunda-platform/properties/ListenerProps.js
> +    return { event: type };
Note that we do not clean up the event definitions when we change from `timeout` event to something else. Please add a test case that verifies this. It could be a set of actions: create -> timeout -> assignment.

2021-10-05 11:59 UTC, barmac commented on src/provider/camunda-platform/properties/ListenerProps.js
> +  const businessObject = getBusinessObject(listener);
Again, listener is always a business object.

2021-10-05 12:00 UTC, barmac requested changes
Good job overall. I left a couple of comments which need to be addressed before we merge this.

2021-10-05 12:31 UTC, smbea commented on src/provider/camunda-platform/properties/ListenerProps.js
> +    return { event: type };
I cleared the definitions when the type is changed from 'timeout' to something else and added a test case to verify

2021-10-05 12:41 UTC, barmac commented
It works fine. The time out problem should disappear when you rebase on `main`.

2021-10-05 12:41 UTC, barmac approved these changes

2021-10-05 12:42 UTC, merged