fix(element-templates): display proper error label
bpmn-io/bpmn-properties-panel pull request #172
Opened 2021-11-10 11:36 UTC by barmac

Closes #166

2021-11-10 14:32 UTC, barmac commented
Ready for review.

2021-11-11 09:52 UTC, MaxTru commented on test/spec/provider/camunda-platform/Error.spec.js
> +      console.log(asOptionNamesList(select));
```suggestion
```

2021-11-11 09:54 UTC, MaxTru requested changes
Generally works, only minor comments

2021-11-11 09:54 UTC, MaxTru commented on test/spec/provider/element-templates/properties/ErrorProperties.spec.js
> +  it('should display given label', async function() {
Should we not add a testCase to `should show placeholder label if only code is set`? (analog to the plain error implementation

2021-11-15 08:26 UTC, barmac commented on test/spec/provider/camunda-platform/Error.spec.js
> +      console.log(asOptionNamesList(select));
🙈

2021-11-15 08:27 UTC, barmac commented on test/spec/provider/camunda-platform/Error.spec.js
> +      console.log(asOptionNamesList(select));
BTW this is a thing which I'd expect to be caught by the linter 🗡️

2021-11-15 08:33 UTC, MaxTru commented on test/spec/provider/camunda-platform/Error.spec.js
> +      console.log(asOptionNamesList(select));
True

2021-11-15 08:34 UTC, barmac commented on test/spec/provider/element-templates/properties/ErrorProperties.spec.js
> +  it('should display given label', async function() {
I'll add it.

2021-11-15 13:30 UTC, barmac commented
Ready for re-review.

2021-11-16 13:55 UTC, nikku commented
General question:

* Is there a way we can try that one out in the test suite? I'd assume `npm run start:platform` makes templates available to me, but it does not.

2021-11-16 13:59 UTC, nikku commented
Does not match existing behavior at the moment. If we want to improve beyond properties-panel@current we could display <unnamed> (code=foo) for errors without a name, but a code. 

Empty feels odd in this case, as the code is there:

![Uploading image.png…]()

2021-11-16 13:59 UTC, nikku commented
Cf. attached screens from the old implementation: https://github.com/bpmn-io/bpmn-properties-panel/issues/166#issuecomment-970293459

2021-11-16 14:00 UTC, nikku commented
Looks fine implementation wise :+1:

2021-11-16 14:32 UTC, barmac commented
> General question:
> 
> * Is there a way we can try that one out in the test suite? I'd assume `npm run start:platform` makes templates available to me, but it does not.

`npm run start:templates`

2021-11-16 14:35 UTC, barmac commented
Let's display then:

| error name | error code | label |
| ----------- | ----------- | ----| 
| name | 500 | name (code=500) |
| name | | name |
| | 500 | \<unnamed> (code=500) |
| | | \<unnamed> |

2021-11-16 17:18 UTC, barmac commented
@nikku Implemented. I will also apply it to changes in https://github.com/bpmn-io/bpmn-properties-panel/pull/161

2021-11-16 18:34 UTC, nikku approved these changes

2021-11-16 18:34 UTC, merged